name: Link Checker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sunday at 00:00

jobs:
  link-checker:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress "./**/*.md"
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
