name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-md:
    runs-on: ubuntu-latest
    name: Lint Markdown content
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          config: ".markdownlint.yaml"
          globs: "**/*.md"

  lint-editorconfig:
    runs-on: ubuntu-latest
    name: Lint for editorconfig violations
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7

      - name: Check for editorconfig violations
        uses: editorconfig-checker/action-editorconfig-checker@v2

  lint-markdown-toc:
    runs-on: ubuntu-latest
    name: Lint for Table of Contents
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install markdown-toc
        run: npm install -g markdown-toc

      - name: Update TOC
        run: markdown-toc --bullets "-" -i README.md

      - name: Check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Please run 'markdown-toc --bullets \"-\" -i README.md' and commit the changes."
            git diff
            exit 1
          fi
